name: VERA Build Protocol

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install Dependencies (Smart Mode)
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel
        
        # 1. Install pipwin and refresh the cache (Crucial Step)
        pip install pipwin
        pipwin refresh
        pipwin install pyaudio
        
        # 2. Install the rest
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build VERA Executable
      run: |
        # --clean clears the cache
        # --hidden-import=pyaudio forces the audio driver to load
        pyinstaller --name VERA_OS --onefile --windowed --clean --add-data "head.gif;." --collect-all customtkinter --hidden-import=comtypes.stream --hidden-import=pyaudio interface.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: VERA_Release_Build
        path: dist/VERA_OS.exe